name: grookai_vault
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.1
  http: ^1.5.0
  image_picker: ^1.2.0
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.14.0
  image: ^4.2.0
  fl_chart: ^1.1.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/kit_placeholder.png
    - .env
